Gui manual selection of ir
UTAT-AeRo/vision_201819 pull request #10
Opened 2018-12-16 05:18 UTC by ianc999

Manual-Filter-GUI.py is now completed. Please review!

2018-12-17 21:11 UTC, levmckinney requested changes
Overall this looks pretty good but it needs to take command line arguments and needs more documentation. It would also be good to add a script for installing dependencies.

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/GUI.py
> +import tkinter;
Add a description of what this file does. In the form
`"""This is module makes a GUI for sorting solar panels ...."""`
Doesn't need to be to long just a few sentences but its to help people reviewing your code and anyone working on it in the future understand what it does. See the example module and projection module for examples of how this should look.

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/Manual-Filter-GUI.py
> +import tkinter
Same thing with doc string for this module.

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/Manual-Filter-GUI.py
> +input_file = open('C:/Users/aa123/Desktop/input.json')
This probably should not be hard coded. This is where your code should use comandline args. See detect.py for examples of how to do this.

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/Manual-Filter-GUI.py
> +def hello():
Do you still nead this?

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/Manual-Filter-GUI.py
> +    dump(data, write_file)
Add new line to the end of file.

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/Manual-Filter-GUI.py
> +def handle_btn_click_yes():
Good name but it would be nice to have a doc string.

2018-12-17 21:11 UTC, levmckinney commented on src/task1/filter-module/Manual-Filter-GUI.py
> +def handle_btn_click_no():
Same here with the doc string.

2019-02-26 22:02 UTC, Timothylock commented
Closing due to age

2019-02-26 22:02 UTC, closed without merging