Module to convert file directory to JSON
UTAT-AeRo/vision_201819 pull request #17
Opened 2019-01-07 00:37 UTC by Timothylock

This looks familiar :) 

The ID Significant changes can use the same module as the Locate IR points with the difference that all the images should be fed into it. This module is a "hack" and given a directory, will generate an output json that can be fed into the Locate IR points module.

2019-01-07 00:39 UTC, Timothylock commented
README will come before merge! And I mean it this time lol

2019-01-07 23:45 UTC, xiejxie requested changes
Btw should this be an entire module on it's own? Wouldn't it be better to have it as a function in some common file?

2019-01-07 23:45 UTC, xiejxie commented on src/task1/sig-changes-json-file-listing/listdirjson.py
> +    parser = argparse.ArgumentParser(description='Detect broken solar panels')
;)

2019-02-26 22:04 UTC, Timothylock commented
@xiejxie  Is this still needed? If not, feel free to close this PR

2019-03-13 05:16 UTC, Timothylock commented
Closing

2019-03-13 05:16 UTC, closed without merging